import crypto from 'node:crypto';

const env = process.env;
const isProd = env.NODE_ENV === 'production';
// A shared test server: production build, but demo data, OTP shown on screen and
// demo payments, so the team can try it without SMS or Razorpay. Never for real patients.
const staging = env.STAGING === 'true';

function secret(name) {
  if (env[name]) return env[name];
  if (isProd) throw new Error(`${name} must be set in production`);
  // Development only: a fresh random secret per run (tokens reset on restart).
  return crypto.randomBytes(32).toString('hex');
}

function json(name) {
  try {
    return JSON.parse(env[name] || '{}');
  } catch {
    throw new Error(`${name} must be JSON, e.g. {"otp":"1107..."}`);
  }
}

export const config = {
  isProd,
  staging,
  port: Number(env.PORT || 4000),
  // How many proxies (load balancer, nginx) sit in front of the app. Rate limits
  // use the client IP from X-Forwarded-For, so this must match the real setup:
  // too high and anyone can fake their IP to dodge the limits. "false" = none.
  trustProxy: env.TRUST_PROXY === 'false' ? false : Number(env.TRUST_PROXY || 1),
  corsOrigins: (env.CORS_ORIGINS || 'http://localhost:5173').split(',').map((s) => s.trim()),
  databaseUrl: env.DATABASE_URL || '',
  pgliteDir: env.PGLITE_DIR || './.data/pglite',
  jwtSecret: secret('JWT_SECRET'),
  idHashSecret: secret('ID_HASH_SECRET'),
  gatewaySecret: secret('GATEWAY_SECRET'),
  otpDevEcho: (!isProd || staging) && env.OTP_DEV_ECHO !== 'false',
  smsProvider: env.SMS_PROVIDER || 'console',
  // India DLT: the entity ID and a JSON map of template name → DLT template ID.
  smsSenderId: env.SMS_SENDER_ID || '',
  smsDltEntityId: env.SMS_DLT_ENTITY_ID || '',
  smsDltTemplates: json('SMS_DLT_TEMPLATES'),
  smsRetryMs: 3000,
  twilioSid: env.TWILIO_ACCOUNT_SID || '',
  twilioToken: env.TWILIO_AUTH_TOKEN || '',
  twilioFrom: env.TWILIO_FROM || '',
  twilioMessagingService: env.TWILIO_MESSAGING_SERVICE_SID || '',
  smsGatewayNumber: env.SMS_GATEWAY_NUMBER || '+910000000000',
  missedCallNumber: env.MISSED_CALL_NUMBER || '+910000000001',
  anthropicKey: env.ANTHROPIC_API_KEY || '',

  // Files: local disk in development, S3 when S3_BUCKET is set.
  uploadDir: env.UPLOAD_DIR || './.data/uploads',
  s3Bucket: env.S3_BUCKET || '',
  s3Region: env.AWS_REGION || 'ap-south-1',
  awsRegion: env.AWS_REGION || 'ap-south-1',

  // Payments: Razorpay when keys are set; otherwise a demo "mock" payment (never in production).
  razorpayKeyId: env.RAZORPAY_KEY_ID || '',
  razorpayKeySecret: env.RAZORPAY_KEY_SECRET || '',
  razorpayWebhookSecret: env.RAZORPAY_WEBHOOK_SECRET || '',

  // Medicine reminders (Web Push). Keys are generated by `npm run setup`.
  vapidPublicKey: env.VAPID_PUBLIC_KEY || '',
  vapidPrivateKey: env.VAPID_PRIVATE_KEY || '',
  vapidSubject: env.VAPID_SUBJECT || 'mailto:admin@example.org',

  // Bhashini (Government of India) speech-to-text for SOS voice messages.
  bhashiniUserId: env.BHASHINI_USER_ID || '',
  bhashiniApiKey: env.BHASHINI_API_KEY || '',
  bhashiniPipelineId: env.BHASHINI_PIPELINE_ID || '',

  // Sessions: patients stay signed in for 30 days; staff sessions are short.
  patientSessionDays: 30,
  // Sign-in attempts per device (IP) per 15 minutes.
  authRateLimit: Number(env.AUTH_RATE_LIMIT || 30),
  staffSessionHours: 12,

  // Video calls: STUN is enough on most networks; TURN is needed behind strict mobile NATs.
  iceServers: [
    { urls: 'stun:stun.l.google.com:19302' },
    ...(env.TURN_URL ? [{ urls: env.TURN_URL, username: env.TURN_USERNAME, credential: env.TURN_CREDENTIAL }] : []),
  ],
};
